services:
  - type: web
    name: lisa-api
    runtime: python
    pythonVersion: 3.10.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
